export enum GameEventType {
  PLAYER_JOIN_GAME,
  START_GAME,
  CHOOSE_ACTION,
  CONFIRM_ACTION,
  CHALLENGE_ACTION,
  BLOCK_ACTION,
  ACCEPT_BLOCK,
  CHALLENGE_BLOCK,
  PLAYER_LOSE_CARD,
  PLAYER_REVEAL_CARD,
  WELCOME,
  PAUSE_GAME,
  RESUME_GAME,
  PLAYER_DISCONNECT,
  PLAYER_RECONNECT,
}

export enum GameActionMove {
  NONE,
  INCOME,
  COUP,
  FOREIGN_AID,
  STEAL,
  ASSASSINATE,
  TAX,
  EXCHANGE,
  LOSE_CARD,
}
